### ISSUE TITLE
Set application_name and application_version

### ISSUE THREAD

**Issue by erjohnso** [chef/knife-google#100]
Sorry I missed this in the initial review.

Similar to the comment/request for kitchen-google, let's set the application_name to `knife-google` and pick up the version to set for application_version.  The old version used this value, so let's carry this forward with the re-write.

Looks like the change needs to happen here: https://github.com/chef/knife-google/blob/1a1a61a05959d13d57d43880be5e0025d09d3bcd/lib/chef/knife/cloud/google_service.rb#L44

Here's the pointer to setting client options: https://github.com/google/google-api-ruby-client/blob/e8481dd14dc2af0667866a319832dc9adc8d54bf/lib/google/apis/options.rb#L32

/cc @adamleff

**Comment by adamleff** [comment]
Totally reasonable, I'll take care of this.

**Comment by erjohnso** [comment]
Thanks Adam!

**Comment by adamleff** [comment]
PR #101 opened for this.
