### ISSUE TITLE
support multiple --local-ssd interfaces

### ISSUE THREAD

**Issue by majuscule** [chef/knife-google#105]
Such as

``` bash
gcloud compute instances create $MACHINE \
    --machine-type n1-highmem-32 \
    --local-ssd interface=nvme \
    --local-ssd interface=nvme \
    --local-ssd interface=nvme \
    --local-ssd interface=nvme \
    ...
```

**Comment by adamleff** [comment]
Hi, @majuscule! There are currently no plans for us to add this in, but pull requests are certainly welcome! I will leave this issue open in case you or someone else wishes to contribute this feature to knife-google.

Thanks!
~Adam
