### ISSUE TITLE
Google::Apis::ClientError

### ISSUE THREAD

**Issue by kidlab** [chef/knife-google#107]
I am using `knife-google-2.2.0` gem, looks like some commands do not work anymore, such as `google server list`:
```
knife google server list --gce-project mytest-app --gce-zone asia-east1-c
```

Output:
```
ERROR: Google::Apis::ClientError: notFound: The resource 'projects/mytest-app' was not found
```

**Comment by dheerajd-msys** [comment]
@kidlab ,
I am able to run this command successfully. How do you provide the `google-compute.json` file to your command?
You may need to set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable with the full path to that file.

Also check if project is created and you have permission to access it.

**Comment by abhishekkr** [comment]
My `knife-google-2.2.0` also suddenly started failing for a command that was working for long.
I've gce utils working, so no issues with credentials. This same setup was working till few weeks back.
Defaults for Project, Zone for Googel Cloud are all correct.

When I tried tracking source of `raise`, it happens in `knife-google-2.2.0/lib/chef/knife/cloud/google_service.rb` in method `check_api_call` at `rescue Google::Apis::ClientError`

The error comes like
* `ERROR: RuntimeError: Invalid machine type: n1-standard-1`

command used
```
knife google server create "$_MACHINE_NAME" -E "$_MACHINE_ENVIRONMENT" -Z "$_MACHINE_ZONE" -m "$_MACHINE_TYPE" -T "a-tag-to-give" -I "$_MACHINE_IMAGE" --gce-public-ip 'None' --gce-use-private-ip --gce-boot-disk-autodelete --gce-boot-disk-size ${_MACHINE_DISKSIZE} --gce-metadata sshKeys='someone:ssh-rsa AAAA_MY_PUBLIC_KEY someone@abk' -x "someone" -i "${_MY_PRIVATE_KEY}" --no-host-key-verify -r 'recipe[mycookbook]' -c "${MY_KNIFE_RB}"
```

**Comment by dheerajd-msys** [comment]
@abhishekkr ,
I checked all possible values and command run fine for me. Machine is being created of type `n1-standard-1`
Could you please share all the actual values used in your command instead of variables ? So that I can verify.

**Comment by abhishekkr** [comment]
@dheerajd-msys my bad, should have updated here... was reviewing my profile funcs, it was an assignment issue due to bad refactoring

**Comment by NimishaS** [comment]
@kidlab , @abhishekkr, Can you please close this if it's not an issue?

**Comment by abhishekkr** [comment]
@NimishaS I can't close the ticket because I didn't open it. Permissions are not such.

**Comment by adamleff** [comment]
I will go ahead and close this ticket now as this does not appear to be an issue with knife-google. Thanks!
