### ISSUE TITLE
No support for GCE image family

### ISSUE THREAD

**Issue by cblecker** [chef/knife-google#108]
When provisioning a new server, you have to specify the full image name, rather than specifying the image family and letting GCE select the most up to date image from that family.

**Comment by adamleff** [comment]
Hi, @cblecker.

In the README:

```
--gce-image: required. The name of the disk image to use when creating the server. knife-google will search your current project for this disk image. If the image cannot be found but looks like a common public image, the public image project will be searched as well. Additionally, this parameter supports the same image aliases that gcloud compute instances create supports. See the output of gcloud compute instances create --help for a full list of aliases.
Example: if you supply a gce-image of centos-7-v20160219, knife-google will first look for an image with that name in your currently-configured project. If it cannot be found, it will look in the centos-cloud project.
This behavior can be overridden with the --gce-image-project parameter.
```

The key item there is this:

> Additionally, this parameter supports the same image aliases that gcloud compute instances create supports.

You should be able to supply `--gce-image centos-7` and get the latest centos-7 image that is available. I just tested this as follows:

```
knife google server create webserver1 --gce-image centos-7 --gce-machine-type n1-standard-1 --gce-public-ip ephemeral --ssh-user aleff --identity-file ~/.ssh/google_compute_engine
image centos-7 is a known alias - using image URL: https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/centos-7-v20160511
Creating instance...

Current status: PENDING.
Current status: RUNNING..
```

Hope that helps. Please let us know.

~Adam

**Comment by cblecker** [comment]
Hi @adamleff,
It seems like some versions work with the [static aliases from the gcloud tool](https://cloud.google.com/sdk/gcloud/reference/compute/instances/create) that way (Centos 7 like your test, and Ubuntu 14.04), but other versions to not (Ubuntu 16.04, for example). The main GCE documentation also doesn't suggest using those aliases, it exclusively refers to the image-family option both [here](https://cloud.google.com/compute/docs/instances/create-start-instance#publicimage) and [here](https://cloud.google.com/compute/docs/images).

Perhaps they are going to phase out the aliases in favour of the image-family option?

Cheers,
Christoph

**Comment by adamleff** [comment]
I'm just guessing, but the image families look an awful lot like the existing image aliases. :) I bet they shifted the logic from each client needing to grab images from a project and make the determination on what the latest is and instead now offer the "image family" as a way of doing that server-side.

The Google API does indeed support image family:

https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/compute_v1/classes.rb#L477-L494

If you'd like to take a stab at submitting a PR for this, that would be great. Otherwise, we'll keep this issue open in hopes that someone can free up cycles to add that functionality in the future.

/cc @chef/partner-engineering

**Comment by nelsonjr** [comment]
I can look into that. Can you assign it to me?

**Comment by erjohnso** [comment]
@adamleff - I don't see @nelsonjr in the list. Can we get him added to our team?

**Comment by adamleff** [comment]
@erjohnso done! Invite sent. :)

**Comment by erjohnso** [comment]
Thanks @adamleff!

**Comment by nelsonjr** [comment]
https://github.com/chef/knife-google/pull/109

**Comment by nelsonjr** [comment]
Hi! It seems that the build job in PR https://github.com/chef/knife-google/pull/109 failed while installing gems, so allegedly unrelated to my changes. But I do not have the privileges to restart the job. Can someone with power to do so trigger it so we can be on the safe side? Thanks!

**Comment by jamesc** [comment]
@nelsonjr I just restarted the travis job.

**Comment by cblecker** [comment]
Thanks for the fix, @nelsonjr!

@adamleff: I opened #110 to version bump the gem so that this change can take effect, and fix Travis that was failing due to a deprecated Ruby version. Mind having a look when you get a chance? Thanks!

**Comment by jjasghar** [comment]
@cblecker I'll take this and get this resolved ASAP.

**Comment by cblecker** [comment]
Hey @jjasghar --
Any update on this? :)

**Comment by jjasghar** [comment]
Been traveling for the past couple weeks, i should be doing some engineering time here starting after labor day. Updates when i get them.

**Comment by cblecker** [comment]
Sounds great. Thanks for the update!

**Comment by cblecker** [comment]
Hi @jjasghar --
Any update on this and #110 ?

**Comment by jjasghar** [comment]
Wow, this slipped through the cracks. I'll take some time ASAP and validate and merge, and release ASAP. Sorry about that.

**Comment by cblecker** [comment]
Thanks for the merge, @jjasghar! The build is still failing, but I think that's because #111 needs a merge too (but needs merge conflicts resolved -- didn't notice that @tas50 had put that in 4d ago, or I would have just removed my attempts to fix Travis from the PR).

**Comment by chefdemo1** [comment]
Crap missed that. I'll get it fixed and push up another patch release.

**Comment by jjasghar** [comment]
Heh, oops, that was me ^^

**Comment by jdstone-ig** [comment]
This issue seems to have popped back up.  When I run
```
knife google server create <HOSTNAME> -E <ENV> --gce-boot-disk-size 160 --gce-boot-disk-ssd --gce-image ubuntu-1804-lts --gce-machine-type n1-standard-2 --gce-project <PROJECT> --gce-public-ip ephemeral --gce-zone <ZONE>
```
I receive the following error.  It appears as GCE image family names are not accepted.
```
Searching public image project ubuntu-os-cloud for image ubuntu-1804-lts
ERROR: RuntimeError: Invalid image: ubuntu-1804-lts - check your image name, or set an image project if needed
```
When running `gcloud compute instances create --help` as suggested in this issue, `Image Aliases` no longer appear in the help information, only `image`, `image-family`, and `image-project`.
