### ISSUE TITLE
knife server create fails if no --gce-public-ip option is supplied

### ISSUE THREAD

**Issue by nikolaybotevsc** [chef/knife-google#116]
⚡ ~$ which knife
/Users/nikolay.botev/.rvm/gems/ruby-2.3.3@chef/bin/knife
⚡ ~$ ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
⚡ ~$ knife --version
Chef: 12.16.42

⚡ ~$ knife google     server create       $hostname             -Z $zone         -i ~/.ssh/google_compute_engine     [... other arguments ...]  --gce-service-account-scopes 'https://www.googleapis.com/auth/devstorage.read_write' -VV
INFO: Using configuration from /Users/nikolay.botev/.chef/knife.rb
/Users/nikolay.botev/.rvm/gems/ruby-2.3.3@chef/gems/knife-google-3.1.0/lib/chef/knife/cloud/google_service.rb:248:in `downcase!': can't modify frozen String (RuntimeError)
	from /Users/nikolay.botev/.rvm/gems/ruby-2.3.3@chef/gems/knife-google-3.1.0/lib/chef/knife/cloud/google_service.rb:248:in `valid_public_ip_setting?'
	from /Users/nikolay.botev/.rvm/gems/ruby-2.3.3@chef/gems/knife-google-3.1.0/lib/chef/knife/cloud/google_service.rb:216:in `validate_server_create_options!'
	from /Users/nikolay.botev/.rvm/gems/ruby-2.3.3@chef/gems/knife-google-3.1.0/lib/chef/knife/cloud/google_service.rb:113:in `create_server'
	from /Users/nikolay.botev/.rvm/gems/ruby-2.3.3@chef/gems/knife-cloud-1.2.1/lib/chef/knife/cloud/server/create_command.rb:68:in `execute_command'
	from /Users/nikolay.botev/.rvm/gems/ruby-2.3.3@chef/gems/knife-cloud-1.2.1/lib/chef/knife/cloud/command.rb:51:in `run'
	from /Users/nikolay.botev/.rvm/gems/ruby-2.3.3@chef/gems/chef-12.16.42/lib/chef/knife.rb:443:in `block in run_with_pretty_exceptions'
	from /Users/nikolay.botev/.rvm/gems/ruby-2.3.3@chef/gems/chef-12.16.42/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /Users/nikolay.botev/.rvm/gems/ruby-2.3.3@chef/gems/chef-12.16.42/lib/chef/knife.rb:442:in `run_with_pretty_exceptions'
	from /Users/nikolay.botev/.rvm/gems/ruby-2.3.3@chef/gems/chef-12.16.42/lib/chef/knife.rb:219:in `run'
	from /Users/nikolay.botev/.rvm/gems/ruby-2.3.3@chef/gems/chef-12.16.42/lib/chef/application/knife.rb:156:in `run'
	from /Users/nikolay.botev/.rvm/gems/ruby-2.3.3@chef/gems/chef-12.16.42/bin/knife:25:in `<top (required)>'
	from /Users/nikolay.botev/.rvm/gems/ruby-2.3.3@chef/bin/knife:22:in `load'
	from /Users/nikolay.botev/.rvm/gems/ruby-2.3.3@chef/bin/knife:22:in `<main>'
	from /Users/nikolay.botev/.rvm/gems/ruby-2.3.3@chef/bin/ruby_executable_hooks:15:in `eval'
	from /Users/nikolay.botev/.rvm/gems/ruby-2.3.3@chef/bin/ruby_executable_hooks:15:in `<main>'

**Comment by nikolaybotevsc** [comment]
⚡ ~$ gem list knife-google

*** LOCAL GEMS ***

knife-google (3.1.0)

**Comment by qorpus** [comment]
yep I get the exact same issue

`dave@laptop:~/dev$ knife google server create davetest --gce-boot-disk-ssd --gce-boot-disk-size 200 --gce-image ubuntu-1604-xenial-v20161130 --gce-project rato-145318 --gce-zone us-west1-a --gce-machine-type n1-standard-1 --ssh-user dave --identity-file ~/.ssh/id_rsa
WARNING: No knife configuration file found
ERROR: RuntimeError: can't modify frozen String
`
then if i run it with --public-ip ephemeral it works

`^Cdave@dave-meta-lap:~/dev/workspace/tenen$ knife google server create davetest --gce-boot-disk-ssd --gce-boot-disk-size 200 --gce-image ubuntu-1604-xenial-v20161130 --gce-project rato-145318 --gce-zone us-west1-a --g-machine-type n1-standard-1 --ssh-user dave --identity-file ~/.ssh/id_rsa --gce-public-ip ephemeral
WARNING: No knife configuration file found
Searching public image project ubuntu-os-cloud for image ubuntu-1604-xenial-v20161130
Creating instance...

Current status: PENDING.
Current status: RUNNING......

Instance created!
Instance Name: davetest
Status: RUNNING
Machine Type: n1-standard-1
Project: dave-12356
Zone: us-west1-a
Network: default
Private IP: 99.99.999
Public IP: 999.999.99.999
Bootstrapping the server by using bootstrap_protocol: ssh and image_os_type: linux
`

**Comment by kapilchouhan99** [comment]
@nikolaybotevsc @qorpus Please try with the latest version of `knife-google`, it is already fixed in the latest version, I have verified it, it is working fine.
Please let me know if you face any issue.
Thank you.

**Comment by kapilchouhan99** [comment]
Fixed this issue in this PR: https://github.com/chef/knife-google/pull/119
