### ISSUE TITLE
how do i mount a disk on an instance which i am creating

### ISSUE THREAD

**Issue by wallydrag** [chef/knife-google#120]
# Version:
:ref => "800f000262f71a28e588308be4279a0c4140bca2"

# Environment: 
on mac OS sierra

# Scenario:
I am trying to create instance with a separate partition with a disk mounted on top of it. I am able to create instances with just boot disk otherwise

**Comment by kapilchouhan99** [comment]
Hi @wallydrag, We have an option `--gce-additional-disks` to attach additional disks in an instance, in this option we pass disk names of additional disks with comma-separated.

example:
`knife google server create kpl-8 --gce-image centos-7-v20160219 --gce-machine-type n1-standard-1 --gce-public-ip ephemeral --ssh-identity-file /.ssh/id_rsa --gce_project "chef-msys" --gce_zone "us-central1-a" --connection-port 22 --connection-protocol ssh --image-os-type linux --connection-user msys --gce-additional-disks "disk-1,disk-2"`

In this example we have two additional disks `disks-1` and `disk-2` which have already created in [compute disks](https://console.cloud.google.com/compute/disks)

Please let me know if you are facing any issue.
Thank you.

**Comment by shindemahendra** [comment]
@wallydrag 
Please confirm we good to close this issue if it is not impacted now.

**Comment by Vasu1105** [comment]
We can close this for now. @wallydrag feel free to open this if you face any issues.
