### ISSUE TITLE
Dependency Conflict on MacOS

### ISSUE THREAD

**Issue by erictchiu** [chef/knife-google#124]
# Version:

knife-google 1.3.1

$ chef -v
Chef Development Kit Version: 2.3.4
chef-client version: 13.4.24
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.18.0
inspec version: 1.40.0

# Environment: 
MacOS X 10.9.3

# Scenario:

Installing from ChefDK, install is successful but dependency prevents knife from executing.
$ chef gem install knife-google
Fetching: knife-google-3.1.1.gem (100%)
WARNING:  You don't have /Users/.chefdk/gem/ruby/2.4.0/bin in your PATH,
	  gem executables will not run.
Successfully installed knife-google-3.1.1

# Steps to Reproduce:
Install knife-google from master on MacOS.

# Expected Result:

knife should run commands

# Actual Result:

$knife google
/opt/chefdk/embedded/lib/ruby/2.4.0/rubygems/specification.rb:2293:in `raise_if_conflicts': Unable to activate knife-google-3.1.1, because chef-13.4.19 conflicts with chef (~> 12.0), google-api-client-0.8.7 conflicts with google-api-client (~> 0.9.0) (Gem::ConflictError)
	from /opt/chefdk/embedded/lib/ruby/2.4.0/rubygems/specification.rb:1413:in `activate'
	from /opt/chefdk/embedded/lib/ruby/2.4.0/rubygems.rb:220:in `rescue in try_activate'
	from /opt/chefdk/embedded/lib/ruby/2.4.0/rubygems.rb:213:in `try_activate'
	from /opt/chefdk/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /opt/chefdk/embedded/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/echiu/.chefdk/gem/ruby/2.4.0/gems/knife-google-3.1.1/lib/chef/knife/google_disk_create.rb:22:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife/core/subcommand_loader.rb:85:in `load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife/core/subcommand_loader.rb:85:in `block in load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife/core/subcommand_loader.rb:85:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife/core/subcommand_loader.rb:85:in `load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife/core/subcommand_loader.rb:95:in `load_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife/core/subcommand_loader.rb:109:in `command_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife.rb:153:in `subcommand_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife.rb:214:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application/knife.rb:156:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/bin/knife:25:in `<top (required)>'
	from /usr/local/bin/knife:267:in `load'
	from /usr/local/bin/knife:267:in `<main>'
$ chef gem update google-knife

**Comment by darkn3rd** [comment]
ChefDK uses an older version of `google-api-client`, and `knife-google` doesn't require needed gem version, only tries to activate what's there even if not installed.

You can workaround this by installing ChefDK 2.5.3, or `chef gem install -v 0.9.28`.

**Comment by NAshwini** [comment]
Hi @erictchiu,

This issue has been resolved in the latest ChefDK version. I have tested it with `chefDK 2.5.3` & `chefDK 3.0.36`.

Thanks,
Ashwini
