### ISSUE TITLE
Doesn't Detect Default Project

### ISSUE THREAD

**Issue by darkn3rd** [chef/knife-google#128]
# Version:

* knife-google (3.2.0)
* chefdk 2.5.3

# Scenario:

Utilize knife-google with my default configured project.

# Steps to Reproduce:

1. `sudo dpkg -i ${HOME}/Downloads/chefdk_2.5.3-1_amd64.deb`
2. `chef exec gem install knife-google`
3. `knife google server list --gce-zone us-east1-c`

# Expected Result:

Get list of systems in default project.  Expected that tooling could read local configuration environment.

# Actual Result:

```
$ knife google server list --gce-zone us-east1-c
ERROR: The following required parameters are missing: gce_project
ERROR: RuntimeError: The following required parameters are missing: gce_project
```

# Workaround

```bash
knife google server list \
  --gce-zone us-east1-c \
  --gce-project "$(gcloud config list --format 'value(core.project)' 2>/dev/null)"
````

**Comment by jjasghar** [comment]
I’ll be attempting to repo this ASAP.  Updates when I have them.

**Comment by NAshwini** [comment]
Thanks @darkn3rd for raising issue. `Chefdk 2.5.3` is no more supported now as per https://docs.chef.io/versions.html#end-of-life-eol-products.
I tried same scenario with `ChefDK 3.9.0 and knife-google-3.3.7` its working fine.

Please let me know if same issue still persist.

**Comment by Vasu1105** [comment]
We are closing this issue as its fixed in new version of knife-google which is mentioned by @NAshwini please feel free to open it if issue still exist.
