### ISSUE TITLE
Knife google failing to setup

### ISSUE THREAD

**Issue by dpmitchell** [chef/knife-google#40]
Hi, 

I've tried to install knife-google a few times and keep failing at the first hurdle. 

Is there anything obvious here? I think this ties into the beta version of retriable. 

My system is Darwin LONM1KWDKQ4L.local 12.5.0 Darwin Kernel Version 12.5.0: Sun Sep 29 13:33:47 PDT 2013; root:xnu-2050.48.12~1/RELEASE_X86_64 x86_64

Ruby is ruby 1.9.3p448 (2013-06-27 revision 41675) [x86_64-darwin12.5.0]

knife google setup -VV
/Users/daniel.mitchell/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:73:in `require': /Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/retriable-2.0.0.beta2/lib/retriable.rb:16: syntax error, unexpected tLABEL, expecting ')' (SyntaxError)
    max_tries:         config.max_tries,
              ^
/Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/retriable-2.0.0.beta2/lib/retriable.rb:17: syntax error, unexpected tLABEL, expecting '='
    base_interval:     config.base_interval,
                  ^
/Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/retriable-2.0.0.beta2/lib/retriable.rb:18: syntax error, unexpected tLABEL, expecting '='
    max_interval:      config.max_interval,
                 ^
/Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/retriable-2.0.0.beta2/lib/retriable.rb:19: syntax error, unexpected tLABEL, expecting '='
    rand_factor:       config.rand_factor,
                ^
/Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/retriable-2.0.0.beta2/lib/retriable.rb:20: syntax error, unexpected tLABEL, expecting '='
    multiplier:        config.multiplier,
               ^
/Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/retriable-2.0.0.beta2/lib/retriable.rb:21: syntax error, unexpected tLABEL, expecting '='
    max_elapsed_time:  config.max_elapsed_time,
                     ^
/Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/retriable-2.0.0.beta2/lib/retriable.rb:22: syntax error, unexpected tLABEL, expecting '='
    timeout:           config.timeout,
            ^
/Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/retriable-2.0.0.beta2/lib/retriable.rb:23: syntax error, unexpected tLABEL, expecting '='
    on:                config.on,
       ^
/Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/retriable-2.0.0.beta2/lib/retriable.rb:24: syntax error, unexpected tLABEL, expecting '='
    on_retry:          config.on_retry,
             ^
/Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/retriable-2.0.0.beta2/lib/retriable.rb:25: syntax error, unexpected tAMPER, expecting '='
    &block)
     ^
/Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/retriable-2.0.0.beta2/lib/retriable.rb:70: syntax error, unexpected keyword_end, expecting $end
	from /Users/daniel.mitchell/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/google-api-client-0.7.1/lib/google/api_client.rb:20:in `<top (required)>'
	from /Users/daniel.mitchell/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/daniel.mitchell/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/knife-google-1.3.1/lib/google/compute/client.rb:17:in `<top (required)>'
	from /Users/daniel.mitchell/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/daniel.mitchell/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/knife-google-1.3.1/lib/google/compute.rb:29:in `<top (required)>'
	from /Users/daniel.mitchell/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /Users/daniel.mitchell/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /Users/daniel.mitchell/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/knife-google-1.3.1/lib/chef/knife/google_base.rb:16:in `<top (required)>'
	from /Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/chef-11.16.4/lib/chef/knife/core/subcommand_loader.rb:34:in `load'
	from /Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/chef-11.16.4/lib/chef/knife/core/subcommand_loader.rb:34:in `block in load_commands'
	from /Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/chef-11.16.4/lib/chef/knife/core/subcommand_loader.rb:34:in `each'
	from /Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/chef-11.16.4/lib/chef/knife/core/subcommand_loader.rb:34:in `load_commands'
	from /Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/chef-11.16.4/lib/chef/knife.rb:120:in `load_commands'
	from /Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/chef-11.16.4/lib/chef/knife.rb:168:in `run'
	from /Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/chef-11.16.4/lib/chef/application/knife.rb:139:in `run'
	from /Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/gems/chef-11.16.4/bin/knife:25:in `<top (required)>'
	from /Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/bin/knife:23:in `load'
	from /Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/bin/knife:23:in `<main>'
	from /Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/bin/ruby_executable_hooks:15:in `eval'
	from /Users/daniel.mitchell/.rvm/gems/ruby-1.9.3-p448/bin/ruby_executable_hooks:15:in `<main>'

**Comment by paulrossman** [comment]
Closing this issue due to age. If the issue still persists, please open a new issue with details.
