### ISSUE TITLE
For any command "ERROR: ArgumentError: unknown keyword: interval" 

### ISSUE THREAD

**Issue by Blasterdick** [chef/knife-google#42]
$ knife google -VV server list -Z europe-west1-b
/usr/local/rvm/gems/ruby-2.1.2/gems/google-api-client-0.7.1/lib/google/api_client.rb:595:in `execute!': unknown keyword: interval (ArgumentError)
	from /usr/local/rvm/gems/ruby-2.1.2/gems/google-api-client-0.7.1/lib/google/api_client.rb:330:in `discovery_document'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/google-api-client-0.7.1/lib/google/api_client.rb:375:in `discovered_api'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/knife-google-1.3.1/lib/google/compute/client.rb:179:in `compute'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/knife-google-1.3.1/lib/google/compute/resource_collection.rb:73:in `api_resource'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/knife-google-1.3.1/lib/google/compute/resource_collection.rb:47:in `get'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/knife-google-1.3.1/lib/chef/knife/google_server_list.rb:34:in `run'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/chef-11.12.8/lib/chef/knife.rb:492:in `run_with_pretty_exceptions'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/chef-11.12.8/lib/chef/knife.rb:174:in `run'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/chef-11.12.8/lib/chef/application/knife.rb:135:in `run'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/chef-11.12.8/bin/knife:25:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/knife:23:in `load'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/knife:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'

**Comment by paulrossman** [comment]
Closing this issue due to age. If the issue still persists, please open a new issue with details.
