### ISSUE TITLE
Documentation for adding a tag to the server

### ISSUE THREAD

**Issue by mansona** [chef/knife-google#53]
Hi Folks, 

I've just spent a bit of time chasing my tail on how to use this plugin, I didn't see any configuration to setup tags. 

One of my colleagues pointed me in the direction of this page: https://docs.chef.io/plugin_knife_google.html which had everything i needed! Any chance that you could either merge the Readme with this or point to it from the Readme?

Cheers

**Comment by paulrossman** [comment]
Great suggestion. I'm about to submit another PR for an ssd boot disk
argument. I'll update the readme too.

**Comment by paulrossman** [comment]
@mansona what configuration options specifically were you encountering problems with? Both seemed roughly the same. Thanks.

**Comment by mansona** [comment]
Sorry maybe I wasn't completely clear on this. We needed to apply a tag to the server on build using this parameter: ```-T TAG1,TAG2,TAG3, --gce-tags TAG1,TAG2,TAG3``` 

My issue wasn't that there was anything wrong with this plugin but instead that these parameters were not documented at all on the Github Readme. Also there was no link in the readme to this page: https://docs.chef.io/plugin_knife_google.html

My personal view is that there shouldn't be 2 differing documentations for how to use this plugin in 2 different places, instead they should either be 100% the same or one should refer to the other and for it to be complete. Do you follow?

**Comment by paulrossman** [comment]
Ah, got it. Great suggestion. I agree, having two sets of documentation are confusing. There is a new gem that I've been trying out recently to help automate writing README.md. I'll take another look next week, possible use that other gem (can't remember the name of it right now) and attempt to combine the two readmes so this gets cleaned up.

**Comment by adamleff** [comment]
Hello! I'm going to close out this issue. `--gce-tags` is documented in both the README and the `--help` output. Thank you!
