### ISSUE TITLE
400 Error from Google During 'knife google setup'

### ISSUE THREAD

**Issue by SimonKaluza** [chef/knife-google#55]
When I run the `knife google setup` command and proceed with the prompts, I am able to successfully enter and follow the steps until it asks to

 "Copy and paste the following url in your brower and allow access. Enter the resulting authorization code below."

At this point, I navigate to the URL, but Google gives me that broken down robot HTTP error page with a 400 status code that reads as follows:

```
400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request: urn:ietf:wg:oauth:2.0:oob did not match a registered redirect URI.
```

Here are the detailed prompts (with sensitive information removed redacted by `**REDACTED**`):

```
$ knife google setup
Enter Project ID (ex: my-gce-project): **REDACTED**
Enter Client ID (ex: 123abc4.apps.googleusercontent.com): **REDACTED**
Enter Client secret: **REDACTED**
Copy and paste the following url in your brower and allow access. Enter the resulting authorization code below.

https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=**REDACTED**&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&scope=https://www.googleapis.com/auth/compute%20https://www.googleapis.com/auth/compute.readonly%20https://www.googleapis.com/auth/devstorage.full_control%20https://www.googleapis.com/auth/devstorage.read_only%20https://www.googleapis.com/auth/devstorage.read_write%20https://www.googleapis.com/auth/devstorage.write_only%20https://www.googleapis.com/auth/userinfo.email


Authorization code: 
```

Since the URL above returns that HTTP 400 redirect_uri_mismatch I cannot get any farther.

**Comment by paulrossman** [comment]
Thanks for the report. I'm taking a look at this now.

**Comment by paulrossman** [comment]
I'm not seeing a 400 and the command completes as expected.

**Comment by SimonKaluza** [comment]
I wonder if it's a bug that's unique to my user ID or client ID.  Or perhaps it arose because I did it on a browser session that has multiple Google user sessions cached (though it allowed me to select the correct user ID before navigating to the 400 error)...  I will try again tomorrow on an incognito browsing session.

Does your authorization code URL include a query paramter like mine that says `redirect_uri=urn:ietf:wg:oauth:2.0:oob`?  This seems to be the part the error message is referencing.

**Comment by hprashar** [comment]
Hitting the same issue while setting up google knife. Do we have any fix for this ?

400. That’s an error.

Error: redirect_uri_mismatch

The redirect URI in the request: urn:ietf:wg:oauth:2.0:oob did not match a registered redirect URI.



I see that when we create Client Id and Secret for Service Accounts there is no redirections URIs mentioned. So where can i change or edit these uris to make this work.

Also tried creating client ID with installed application, which gives a redirect URI. However that eventually failed with Invalid client message.

ERROR: Signet::AuthorizationError: Authorization failed.  Server message:
{
  "error" : "invalid_client"
}

Will really appreciate any help provided here.

**Comment by SimonKaluza** [comment]
Incase anyone is wondering, my workstation is running OSX 10.10 so the problem isn't relegated to Linux installs only.

**Comment by adamleff** [comment]
Hello! With the recent release of knife-google v2.0.0, this should no longer be an issue. We now use the Google Cloud SDK credential files rather than the knife plugin performing its own setup.
