### ISSUE TITLE
ERROR: Image 'ubuntu-1404-trusty-v20150316' not found

### ISSUE THREAD

**Issue by sheldoan** [chef/knife-google#59]
I'm trying to use `knife google server create` to launch a new instance with image `ubuntu-1404-trusty-v20150316`, which is listed as a valid image by `gcloud`:

```
$ gcloud compute images list | grep trusty
ubuntu-1404-trusty-v20150316 ubuntu-os-cloud ubuntu-14-04 READY
```

Is there any way to configure knife to have it look at the same list of images as gcloud?

**Comment by paulrossman** [comment]
Hey @sheldoan, I became aware of this issue earlier this evening and will be looking into this tomorrow. Thanks for notifying us.

**Comment by sheldoan** [comment]
Great thanks

**Comment by paulrossman** [comment]
I updated knife-google to support ubuntu (and a number of other GCE provided os types). Please try v1.4.2. Cheers!

**Comment by sheldoan** [comment]
Works like a charm. Thanks!
