### ISSUE TITLE
knife google hides quota errors from GCE

### ISSUE THREAD

**Issue by mattse** [chef/knife-google#71]
I've been using knife-google for months without error, and today I ran into a strange bug.  I had always been able to do things like `bundle exec knife google server create SERVER_NAME ...`.  But today, I got an error after running that command.  

```
Waiting for the create server operation to complete
.
.
Waiting for the servers to be in running state
ERROR: Google::Compute::ResourceNotFound: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "The resource 'projects/PROJECT_NAME/zones/us-central1-c/instances/mtse-test-xxx' was not found"
   }
  ],
  "code": 404,
  "message": "The resource 'projects/PROJECT_NAME/zones/us-central1-c/instances/mtse-test-xxx' was not found"
 }
}
```

I looked through knife-google's readme, and I was led to the suggestion that I typed in the incorrect "Project ID", or used the "Project ID Number" instead of the Project ID.  After rerunning `knife google setup` multiple times, and recreating multiple new Client ID's, I was getting nowhere.  I finally figured out the issue by trying to create a server through another method.  

```
mtse@mtse-ubiquity-1:~$ gcloud compute instances create mtse-test-gcloud
...
NAME ZONE MACHINE_TYPE PREEMPTIBLE INTERNAL_IP EXTERNAL_IP STATUS
ERROR: (gcloud.compute.instances.create) Some requests did not succeed:
 - Quota 'IN_USE_ADDRESSES' exceeded.  Limit: 23.0
```

So the reason knife-google failed was due to a GCE quota issue, which was totally swallowed up.  It would have been really helpful for knife-google to output that.

**Comment by adamleff** [comment]
In the latest release of knife-google (v2.1.0), we work directly with the operation object which would be used to surface this issue. Any errors encountered when trying to perform an operation on GCE will be surfaced.
