### ISSUE TITLE
Creating a preemptible instance flag feature 

### ISSUE THREAD

**Issue by Blasterdick** [chef/knife-google#72]
It would be great to have an ability to create preemptible instances via knife google. I'm not a programmer, so it's like "feature-request" or so)))

**Comment by adamleff** [comment]
Thanks for your suggestion, and our apologies for the tardiness in our reply. I will implement this (we have the same functionality in [kitchen-google](https://github.com/test-kitchen/kitchen-google) so it's totally reasonable to have it in this knife plugin, too. :)

**Comment by adamleff** [comment]
PR #102 opened to add this feature.
