### ISSUE TITLE
knife-google not setting custom metadata

### ISSUE THREAD

**Issue by yonah-codefresh** [chef/knife-google#74]
Suddenly knife-google is not setting the custom metadata on created instances.
It might be related to a recent update of the gcloud SDK, though I'm not sure.
Adding verbosity (-VVV) to the process doesn't seem to give any interesting clues.
Creating the instance via native gcloud command works.

**Comment by Aliasgar16** [comment]
Could you please provide the knife-google version number from which you are trying the operation.

**Comment by Aliasgar16** [comment]
Hi @yonah-codefresh 

Can you please refer https://github.com/chef/knife-google/issues/37

Thanks

**Comment by NimishaS** [comment]
@yonah-codefresh , can you please verify if the issue still persists for you.

**Comment by yonah-codefresh** [comment]
re: https://github.com/chef/knife-google/issues/37

I've updated gcloud and the problem seems to be resolved

**Comment by NimishaS** [comment]
Thanks @yonah-codefresh
