### ISSUE TITLE
google-api-client dependency is about to break APIs

### ISSUE THREAD

**Issue by mattray** [chef/knife-google#75]
According to the documentation on the google-api-client Gem page on GitHub, they're about to introduce breaking changes with the upcoming 0.9 release. We should either pin our dependency or start working with the 0.9 release candidates before the plugin is broken.
https://github.com/google/google-api-ruby-client/blob/master/MIGRATING.md

**Comment by siddheshwar-more** [comment]
@mattray 
Yeah, we will take care of this. Thank you for pointing this.

**Comment by adamleff** [comment]
Closing this old issue. `knife-google` now uses the 0.9 release of google-api-client.
