### ISSUE TITLE
Can't execute any command with knife

### ISSUE THREAD

**Issue by bighoax** [chef/knife-google#84]
I've installed chef dk and then I did a bundle `gem install knife-google` inside my `chef-repo` folder which I downloaded and unpacked from my chef server starter kit.

I've started with this command :
```
knife google setup
```

And I followed the input necessary including client id/secret etc. And I wanted to test if this is working by just trying to list the zones like this :

```
knife google zone list
```

And I get this error:

```
ERROR: TypeError: no implicit conversion of Time into String
```

Whichever command with `knife google` I execute I get this error, I'm running `ruby-2.2.2.` it's a ruby MRI.

**Comment by Vasu1105** [comment]
@bighoax , we have been able to reproduce this issue. Working on this.

**Comment by bighoax** [comment]
@Vasu1105 thanks, please let me know if I can do something.

**Comment by adamleff** [comment]
Closing this older issue. knife-google v2.1.0 has been released which uses the newer google-api-client and also uses the Google Cloud SDK credentials file, eliminating the need to do a `knife google setup` as was once required.

@bighoax please give the latest knife-google a shot and reopen this issue if you still have difficulty running these knife commands. Thanks!
