### ISSUE TITLE
Server create command returns error

### ISSUE THREAD

**Issue by c0mrade** [chef/knife-google#86]
I had the exact same issue as described in https://github.com/chef/knife-google/issues/84

Took the solution that was provided by developer and applied it to my own fork of this repo. This enabled me to perform other commands which I wasn't able before like listing zones etc.

So I tried to provision an instance, this is command execution and the relevant log part (removed bunch of dots):

```
knife google server create www1 -m n1-standard-1 -I centos-7-v20150127 -Z us-east1-c
Looking for Image 'centos-7-v20150127' in Project 'xxxxxx-project-114123'
Looking for Image 'centos-7-v20150127' in Project 'centos-cloud'
Found Image 'centos-7-v20150127' in Project 'centos-cloud'
Waiting for the boot disk insert operation to complete
Name: www1
Zone: us-east1-c
Type: pd-standard
Size: 10 gb
Image: centos-7-v20150127
.
Waiting for the create server operation to complete
.
.
.
Waiting for the servers to be in running state
Instance Name: www1
Machine Type: n1-standard-1
Image: centos-7-v20150127
Zone: us-east1-c
Tags: None
Public IP Address: ["104.1xx.xx.xxx"]
Private IP Address: ["10.240.0.8"]

Waiting for server

Waiting for sshd
done
ERROR: knife encountered an unexpected error
This may be a bug in the 'google server create' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `empty?' for nil:NilClass
```

Despite this error it created an instance for me. But wanting to be useful and this time I re-ran the command to create a different instance only with the `-VV` flag so I can post more info here, this is the output:

```
nife google server create -VV www2 -m n1-standard-1 -I centos-7-v20150127 -Z us-east1-c
INFO: Using configuration from /RDX/chef/chef-repo/.chef/knife.rb
Looking for Image 'centos-7-v20150127' in Project 'xxxxxx-project-114123'
Looking for Image 'centos-7-v20150127' in Project 'centos-cloud'
Found Image 'centos-7-v20150127' in Project 'centos-cloud'
Waiting for the boot disk insert operation to complete
Name: www2
Zone: us-east1-c
Type: pd-standard
Size: 10 gb
Image: centos-7-v20150127
.
.
Waiting for the create server operation to complete
.
.
.
.
Waiting for the servers to be in running state
/Library/Ruby/Gems/2.0.0/gems/knife-google-2.0.0/lib/google/compute/client.rb:200:in `dispatch': { (Google::Compute::ResourceNotFound)
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "The resource 'projects/xxxxxx-project-114123/zones/us-east1-c/instances/www2' was not found"
   }
  ],
  "code": 404,
  "message": "The resource 'projects/divine-precinct-114123/zones/us-east1-c/instances/www2' was not found"
 }
}
	from /Library/Ruby/Gems/2.0.0/gems/knife-google-2.0.0/lib/google/compute/resource_collection.rb:47:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/knife-google-2.0.0/lib/chef/knife/google_server_create.rb:616:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/chef-12.5.1/lib/chef/knife.rb:405:in `block in run_with_pretty_exceptions'
	from /Library/Ruby/Gems/2.0.0/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /Library/Ruby/Gems/2.0.0/gems/chef-12.5.1/lib/chef/knife.rb:404:in `run_with_pretty_exceptions'
	from /Library/Ruby/Gems/2.0.0/gems/chef-12.5.1/lib/chef/knife.rb:203:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/chef-12.5.1/lib/chef/application/knife.rb:142:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/chef-12.5.1/bin/knife:25:in `<top (required)>'
	from /usr/local/bin/knife:23:in `load'
	from /usr/local/bin/knife:23:in `<main>'

```

This is completely different error and my instance wasn't created this time.

**Comment by NimishaS** [comment]
@c0mrade , we tried with the patch https://github.com/chef/knife-google/pull/85 but didn't run into any issue while server creation. Please verify the following things:
1. Is your `ssh` key added on the Google compute portal? You can also pass `ssh` key with `-i` option
2. Did u build the gem with the fix on your local machine and then installed it?

**Comment by c0mrade** [comment]
Hi NimishaS

1. I have no problems with creating instances using `gloud compute` command. And I don't mind doing it with that command really, just wanted to bring that up in case that is important for you (it's not for me).
2.  Yes I've applied the fix from #85 locally on my forked copy and I've built the gem and installed it

**Comment by c0mrade** [comment]
@Hi NimishaS this is a problem with chef server version `12.5.1` it's been fixed in master and will probably be in the next release, in the meantime I changed my locally installed chef gem.

Line https://github.com/chef/chef/blob/12.5.1/lib/chef/knife/bootstrap.rb#L425 and so when I change this line to :

```
(config[:run_list] && !config[:run_list].empty?) && !!config[:policy_name]
```

**Comment by adamleff** [comment]
Closing old issue - this has been fixed in recent chef and knife-google releases. Please reopen this issue if you still experience this problem. Our apologies for the delay in any response.
