### ISSUE TITLE
knife google command not working

### ISSUE THREAD

**Issue by vaibhavswarnkar** [chef/knife-google#87]
I'm using windows and I'm receiving following error on running any command of knife google

ERROR: knife encountered an unexpected error
This may be a bug in the 'google server create' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `snake_case' for "Zone":String

Also when I try to check all commands of knife google it gives me following error

FATAL: Cannot find subcommand for: 'google'
Available google subcommands: (for details, knife SUB-COMMAND --help)

**Comment by NimishaS** [comment]
@vaibhavswarnkar , please share the commands that you tried along with the output.

**Comment by vaibhavswarnkar** [comment]
For checking the list of commands available, following is the output

C:\Users\Ghost>knife google
FATAL: Cannot find subcommand for: 'google'
Available google subcommands: (for details, knife SUB-COMMAND --help)

** GOOGLE COMMANDS **
knife google disk create NAME --gce-disk-size N -Z ZONE (options)
knife google disk delete NAME -Z ZONE (options)
knife google disk list -Z ZONE (options)
knife google project list (options)
knife google region list (options)
knife google server create NAME -m MACHINE_TYPE -I IMAGE -Z ZONE (options)
knife google server delete SERVER [SERVER] -Z ZONE (options)
knife google server list -Z ZONE (options)
knife google setup
knife google zone list (options)


For any knife google ---XXXX--- command, it gives following error,

C:\Users\Ghost>knife google zone list
ERROR: knife encountered an unexpected error
This may be a bug in the 'google zone list' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `snake_case' for "Zone":String

**Comment by vaibhavswarnkar** [comment]
Does anyone have solution for this.....??

**Comment by Vasu1105** [comment]
@vaibhavswarnkar : I am getting this issue with released version 1.3.1. It does not exist with master branch.

**Comment by Vasu1105** [comment]
@vaibhavswarnkar  I confirmed with windows too it exist on released version 1.3.1. It does not exist on master branch. You can use master. Please note #88

**Comment by adamleff** [comment]
Closing old issue - this should not be an issue in the latest release (v2.1.0). Thanks!
