### ISSUE TITLE
New Functionality: knife-google unable to spinup servers in subnets

### ISSUE THREAD

**Issue by jameshcoppens** [chef/knife-google#89]
I'm not sure if everyone is aware or not but google has beta'd the release of subnets in virtual networks.  The current version of this gem that I build (2.0.0) doesn't account for spin up in subnets.  I'd like to start the development on getting the ability to spinup servers in subnets going.  Can anyone help in the process of doing this?

**Comment by vjdhama** [comment]
Also waiting for it. :+1:

**Comment by jameshcoppens** [comment]
As soon as I figure out this friggin rspec problem so my builds won't fail I'll try and send a pull request to Nimisah.  Sorry VJ, hold on for one more day bru.

**Comment by adamleff** [comment]
@jameshcoppens this gem just got a recent rewrite to switch from using Fog to Google's google-api-client. It shouldn't be too hard to add subnet support as the NetworkInterface class supports it:

https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/compute_v1/classes.rb#L5233-L5244

**Comment by jameshcoppens** [comment]
<dr dre voice> Oh hell yeah </dr dre voice>

**Comment by jameshcoppens** [comment]
oh hell yeah!

**Comment by adamleff** [comment]
PR #103 has been opened for subnet support

**Comment by jameshcoppens** [comment]
Hey Adam, 
Can I tackle this one?  I've got some spare cycles next week.

**Comment by jameshcoppens** [comment]
Ahh man, it looks like you already tacked the code for it.

**Comment by adamleff** [comment]
Yeah, sorry. I did it for this and kitchen-google at the same time.

**Comment by jameshcoppens** [comment]
What other PRs can I jump on for knife-google?
Jimmy

**Comment by adamleff** [comment]
If you'd like to try your hand at a PR for #97, please feel free. I've already started on a PR for #96, and those are the only two remaining issues in the repo currently.

**Comment by jameshcoppens** [comment]
Hey @adamleff 
Can I still jump on this PR?  I'm sorry I had to address some other dev concerns.  
Jimmmy

**Comment by adamleff** [comment]
This issue (#89) and the PR that addressed it (#103) are already done. If you're talking about #97 then feel free.

**Comment by jameshcoppens** [comment]
Yeah, I'm talking about #97. 

Cool thank you sir.
