### ISSUE TITLE
Support an alias for latest public image

### ISSUE THREAD

**Issue by adamleff** [chef/knife-google#96]
It would be super-handy if a user could specify "centos" and automatically get the latest CentOS image from the centos-cloud project. Supporting the known public image projects in this manner would make for a better user experience.

**Comment by erjohnso** [comment]
Ah cool, thanks Adam! Since you're willing to bring knife close to parity with gcloud for scope aliases, you could do the same thing for image names.

  ```
  # this help page also lists the aliases for images (e.g. centos-7)
  gcloud compute instances create --help
  ```

**Comment by adamleff** [comment]
Yup - that's the intended outcome of this issue :)
