### ISSUE TITLE
Create an "image list" command

### ISSUE THREAD

**Issue by adamleff** [chef/knife-google#97]
New command `knife google image list` should list the images available in the currently-configured project, and then the most recent project for each of the known public image projects and image aliases (i.e. the latest centos-6 image, centos-7 image, etc).

**Comment by jameshcoppens** [comment]
Can you give me until Thursday to figure this one out?

**Comment by adamleff** [comment]
There's no rush. :) I won't touch it.

**Comment by jameshcoppens** [comment]
@adamleff 
Hey Adam, I'm sorry but I got bogged down with some other things.  Can I still tackle this one? 

You know I worked with you at WebMD about 5 years ago, right?
Jimmy

**Comment by jjasghar** [comment]
@jameshcoppens i'd love to see this get done. I started to poke around with this, and found it odd that i couldn't list out the images.

If you'd like to post a PR, I'd be more then willing to CR it and test it out.
